Add controller vibration (#11)
* clear weapon_target in ship_init (fixes #141)

* clear `expected` state in `input_bind` so remapped controls actually work (fixes #132)

* `vec3_is_on_face` angle value test updated to match original code.

* remove erroneous division by 64 in `magnitude` calculation for nose collision
this makes ship nose swing back out toward center of track again (noticeably)

* remove erroneous division by 16 in `magnitude` calculation (wing collision)
this restores the behavior of ship rolling on wing collision with side of track
there may still be other code to tweak as this seems more sensitive than PSX behavior

* use reciprocal multiply as seen in many other lines of rewrite

* another place where angle comparison to 30000 was converted differently

* angular z component computation did not match original source DYNAM.C

* 2 * pi, I also messed up

* scale face normal contribution consistently in floor collision code

* reimplement camera shake

* mistake, messed up roll

* LONG/SHORT_SHAKE -> CAMERA_SHAKE_LONG/SHORT

* fix indentation

* adjust face->normal scaling constant for collision with floor

* another fixed point scaling issue?

* restore original attract mode/demo behavior

With a very small reordering, the original PSX demo behavior is restored (countdown at starting line). Gets rid of the need for the "FIXME" part in the ship loop as well.

* Adjust scaling values in ship to ship collision code

* Update QOA lib

* Add menu option for screen shake

* Allow A_MENU_START for highscore entry; close #133

* Better analog controls; thanks @mickski56; close #77

* add wipegame.exe to .gitignore

* Use sdl2-config for L_FLAGS_SDL

Additional flags passed by 'sdl2-config --libs' fix an undefined reference to WinMain that prevents the target from successfully linking.

* Correct L_FLAGS_SOKOL for MSYS2

libdl and libasound don't exist on Windows. The Sokol build needs gdi32 and ole32 to successfully link.

* Remove unnecessary MSYS define

'__MSYS__' is pre-defined by the MSYS2 environment's toolchains, and should NOT be defined for MINGW32/64, UCRT64, etc.

* Add controller vibration support

---------

Co-authored-by: jnmartin84 <jnmartin84@gmail.com>
Co-authored-by: Dominic Szablewski <dominic@phoboslab.org>
Co-authored-by: J.Ingram <26800139+GirianSeed@users.noreply.github.com>